---
- name: NGINX | Installing NGINX repo rpm
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

- name: Installs nginx web server
  yum: 
    name: nginx
    state: latest

- name: Firewalld rules edit
  firewalld:
    zone: public
    service: http
    permanent: true
    state: enabled
    immediate: yes
  notify: start nginx

- name: Start and enable NGINX (cause ansible bug)
  shell: "{{ item }}"
  with_items:
   - systemctl restart nginx
   - systemctl enable nginx
  tags: nginx

